# 15 Bag of Words
- word count

**Limitation**
- the whole email might cause 100k vector if email contains 100k words
- cannot capture meaning

In [1]:
 import pandas as pd
 import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == "spam" else 0)

In [5]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2, random_state=42)

In [26]:
X_train.shape

(4457,)

In [27]:
X_test.shape

(1115,)

In [28]:
type(y_train)

pandas.core.series.Series

In [29]:
X_train[:5]

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
Name: Message, dtype: object

In [30]:
y_train[:5]

1978    1
3989    0
3935    0
4078    0
4086    1
Name: spam, dtype: int64

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
X_train_cv = vec.fit_transform(X_train.values)

In [33]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
X_train_cv.shape

(4457, 7701)

In [41]:
vec.get_feature_names_out()[4898]

'on'

In [38]:
vec.get_feature_names_out().shape

(7701,)

In [39]:
dir(vec)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [40]:
vec.vocabulary_

{'reply': 5687,
 'to': 6888,
 'win': 7474,
 '100': 258,
 'weekly': 7396,
 'where': 7437,
 'will': 7471,
 'the': 6773,
 '2006': 354,
 'fifa': 2805,
 'world': 7555,
 'cup': 2106,
 'be': 1271,
 'held': 3364,
 'send': 5980,
 'stop': 6460,
 '87239': 694,
 'end': 2568,
 'service': 5999,
 'hello': 3369,
 'sort': 6304,
 'of': 4854,
 'out': 4976,
 'in': 3603,
 'town': 6959,
 'already': 924,
 'that': 6770,
 'so': 6252,
 'dont': 2395,
 'rush': 5825,
 'home': 3441,
 'am': 934,
 'eating': 2504,
 'nachos': 4650,
 'let': 4057,
 'you': 7662,
 'know': 3926,
 'eta': 2627,
 'how': 3487,
 'come': 1902,
 'guoyang': 3258,
 'go': 3140,
 'tell': 6711,
 'her': 3384,
 'then': 6784,
 'told': 6904,
 'hey': 3392,
 'sathya': 5881,
 'till': 6856,
 'now': 4808,
 'we': 7372,
 'dint': 2323,
 'meet': 4392,
 'not': 4797,
 'even': 2638,
 'single': 6147,
 'time': 6857,
 'can': 1629,
 'saw': 5894,
 'situation': 6164,
 'orange': 4945,
 'brings': 1509,
 'ringtones': 5763,
 'from': 2993,
 'all': 911,
 'chart': 1733,
 'heroes': 3387,
 'with': 7502,
 'free': 2958,
 'hit': 3411,
 'each': 2485,
 'week': 7393,
 'pics': 5172,
 'on': 4898,
 'wap': 7337,
 'receiving': 5603,
 'these': 6792,
 'tips': 6863,
 'sitting': 6163,
 'mu': 4604,
 'waiting': 7311,
 'for': 2910,
 'everyone': 2650,
 'get': 3094,
 'my': 4639,
 'suite': 6549,
 'take': 6650,
 'shower': 6096,
 'finish': 2834,
 'liao': 4063,
 'urgent': 7162,
 'your': 7667,
 'mobile': 4515,
 'no': 4763,
 '07808726822': 39,
 'was': 7346,
 'awarded': 1171,
 '000': 1,
 'bonus': 1427,
 'caller': 1612,
 'prize': 5394,
 '02': 8,
 '09': 163,
 '03': 14,
 'this': 6811,
 'is': 3712,
 'our': 4975,
 '2nd': 410,
 'attempt': 1128,
 'contact': 1972,
 'call': 1606,
 '0871': 98,
 '872': 693,
 '9758': 733,
 'box95qu': 1469,
 'probably': 5399,
 'still': 6450,
 'going': 3152,
 'over': 4992,
 'some': 6266,
 'stuff': 6503,
 'here': 3385,
 'wah': 7301,
 'lucky': 4226,
 'man': 4301,
 'save': 5890,
 'money': 4542,
 'hee': 3360,
 'at': 1119,
 'gym': 3264,
 'oh': 4875,
 'lk': 4128,
 'tt': 7023,
 'den': 2231,
 'one': 4904,
 'ends': 2572,
 'cine': 1810,
 'lor': 4176,
 'dun': 2472,
 'wan': 7327,
 'yogasana': 7659,
 'oso': 4967,
 'ok': 4879,
 'if': 3566,
 'havent': 3333,
 'collected': 1887,
 'dough': 2415,
 'pls': 5226,
 'me': 4373,
 'place': 5197,
 'sent': 5988,
 'it': 3724,
 'control': 1985,
 'number': 4821,
 'stupid': 6509,
 'its': 3732,
 'possible': 5296,
 'have': 3330,
 'secret': 5946,
 'admirer': 824,
 'reveal': 5737,
 'who': 7448,
 'thinks': 6806,
 'special': 6337,
 '09065174042': 226,
 'opt': 4936,
 '50': 535,
 'per': 5113,
 'msg': 4588,
 'recd': 5597,
 'cust': 2115,
 'care': 1654,
 '07821230901': 41,
 'amazing': 936,
 'rearrange': 5586,
 'letters': 4060,
 'gives': 3124,
 'same': 5860,
 'meaning': 4377,
 'dormitory': 2405,
 'dirty': 2332,
 'room': 5787,
 'astronomer': 1116,
 'moon': 4555,
 'starer': 6413,
 'eyes': 2720,
 'they': 6797,
 'see': 5955,
 'election': 2546,
 'results': 5726,
 'lies': 4069,
 'lets': 4058,
 'recount': 5616,
 'mother': 4565,
 'law': 4009,
 'woman': 7529,
 'hitler': 3412,
 'eleven': 2549,
 'plus': 5231,
 'two': 7046,
 'twelve': 7039,
 '09090900040': 245,
 'listen': 4112,
 'extreme': 2716,
 'live': 4122,
 'chat': 1738,
 'office': 4865,
 'right': 5754,
 'total': 6950,
 'privacy': 5390,
 'knows': 3929,
 'sic': 6117,
 'listening': 4114,
 '60p': 572,
 'min': 4452,
 '24': 369,
 '7mp': 628,
 '0870753331018': 92,
 'which': 7442,
 'why': 7456,
 'never': 4724,
 'wanted': 7334,
 'any': 995,
 'short': 6081,
 'and': 961,
 'edge': 2512,
 'as': 1086,
 'late': 3994,
 'are': 1051,
 'when': 7433,
 'wil': 7468,
 'reach': 5562,
 'yeah': 7635,
 'diet': 2302,
 'just': 3841,
 'flew': 2864,
 'window': 7477,
 'shit': 6066,
 'thought': 6822,
 'trip': 6995,
 'loooooool': 4172,
 'makes': 4292,
 'much': 4606,
 'more': 4557,
 'sense': 5984,
 'grins': 3224,
 'sofa': 6256,
 'reference': 5626,
 'sleep': 6185,
 'couch': 2019,
 'link': 4100,
 'wasn': 7348,
 'went': 7411,
 'didn': 2296,
 'babe': 1189,
 'celebration': 1700,
 'rents': 5678,
 'sending': 5982,
 'greetings': 3221,
 'joy': 3821,
 'happiness': 3311,
 'do': 2362,
 'gr8': 3193,
 'evening': 2639,
 'armand': 1065,
 'says': 5899,
 'ass': 1105,
 'epsilon': 2605,
 'aiyah': 887,
 'did': 2294,
 'lar': 3987,
 'nydc': 4833,
 'wheellock': 7432,
 'don': 2391,
 'he': 3339,
 'watching': 7358,
 'film': 2821,
 'computer': 1935,
 'but': 1573,
 'heard': 3349,
 'abt': 767,
 'tat': 6674,
 'oops': 4920,
 'sorry': 6303,
 'check': 1748,
 'mind': 4455,
 'picking': 5170,
 'up': 7140,
 'tomo': 6913,
 'half': 3280,
 'eight': 2535,
 'station': 6428,
 'would': 7566,
 'anytime': 1006,
 'friendship': 2980,
 'poem': 5255,
 'dear': 2179,
 'near': 4688,
 'hear': 3348,
 'fear': 2774,
 'cheer': 1755,
 'tear': 6697,
 'always': 932,
 'gud': 3245,
 'ni8': 4738,
 'yar': 7627,
 'else': 2552,
 'll': 4129,
 'thk': 6812,
 'sorts': 6307,
 'funny': 3023,
 'things': 6801,
 'love': 4197,
 'isn': 3719,
 'decision': 2192,
 'feeling': 2783,
 'could': 2022,
 'decide': 2188,
 'life': 4070,
 'simpler': 6138,
 'less': 4053,
 'magical': 4277,
 'those': 6818,
 'were': 7413,
 'exact': 2671,
 'intentions': 3668,
 'erm': 2611,
 'woodland': 7541,
 'avenue': 1161,
 'somewhere': 6281,
 'parish': 5051,
 'magazine': 4274,
 'his': 3409,
 'telephone': 6709,
 'there': 6790,
 'every': 2645,
 'day': 2166,
 'use': 7176,
 'after': 854,
 'lt': 4219,
 'gt': 3240,
 'only': 4910,
 'jus': 3840,
 'hope': 3457,
 'true': 7005,
 'missin': 4483,
 'cos': 2012,
 'really': 5582,
 'him': 3404,
 'haven': 3332,
 'done': 2393,
 'anything': 1004,
 'feel': 2781,
 'guilty': 3255,
 'about': 760,
 'yet': 7649,
 'yup': 7685,
 'paragon': 5042,
 'decided': 2189,
 'whether': 7441,
 'cut': 2121,
 'hmv': 3425,
 '500': 536,
 'pounds': 5310,
 'genuine': 3089,
 'vouchers': 7282,
 'won': 7532,
 'answer': 984,
 'easy': 2500,
 'questions': 5500,
 'play': 5209,
 '86688': 684,
 'info': 3635,
 'www': 7596,
 '100percent': 262,
 'real': 5573,
 'com': 1896,
 'final': 2824,
 'chance': 1716,
 'claim': 1816,
 'ur': 7158,
 '150': 304,
 'worth': 7562,
 'discount': 2340,
 'today': 6894,
 'text': 6744,
 'yes': 7646,
 '85023': 675,
 'savamob': 5889,
 'member': 4406,
 'offers': 4864,
 'cs': 2086,
 'pobox84': 5247,
 'm263uz': 4249,
 '00': 0,
 'subs': 6518,
 '16': 316,
 'sarcasm': 5873,
 'nt': 4812,
 'scarcasim': 5903,
 'wherre': 7440,
 'boytoy': 1476,
 'mr': 4583,
 'sheffield': 6047,
 'wanna': 7330,
 'game': 3045,
 'okay': 4880,
 're': 5561,
 'boss': 1445,
 'nanny': 4665,
 'give': 3122,
 'raise': 5523,
 'prepare': 5354,
 'pleasured': 5222,
 'able': 758,
 'friday': 2975,
 'find': 2828,
 'an': 958,
 'alternative': 929,
 'yr': 7676,
 'term': 6728,
 'good': 3165,
 'morning': 4561,
 'im': 3579,
 'suffering': 6539,
 'fever': 2795,
 'dysentry': 2484,
 'cash': 1673,
 'balance': 1211,
 'currently': 2111,
 'maximize': 4362,
 '150p': 306,
 'cc': 1693,
 '08718720201': 143,
 'po': 5236,
 'box': 1457,
 '114': 273,
 '14': 296,
 'tcr': 6688,
 'w1': 7287,
 'forwarded': 2936,
 'message': 4424,
 'back': 1196,
 'thanks': 6762,
 'them': 6780,
 'accenture': 776,
 'confirm': 1951,
 'want': 7332,
 'buy': 1577,
 'dating': 2163,
 'cal': 1600,
 '09064012103': 216,
 'box334sk38ch': 1464,
 'foreign': 2914,
 'stamps': 6407,
 'whatever': 7427,
 'off': 4856,
 'haha': 3272,
 'receipt': 5598,
 'sound': 6311,
 'gd': 3074,
 'luck': 4224,
 'chikku': 1776,
 'ya': 7620,
 'like': 4081,
 'seconds': 5945,
 'cant': 1640,
 'think': 6802,
 'anyone': 999,
 'spare': 6330,
 'top': 6937,
 'head': 3340,
 'sex': 6012,
 'sexy': 6016,
 'pic': 5167,
 'jordan': 3816,
 '88600': 701,
 'wk': 7512,
 'celeb': 1698,
 'pocketbabe': 5251,
 'co': 1865,
 'uk': 7074,
 '087016248': 81,
 'college': 1891,
 'atten': 1129,
 'class': 1823,
 'freephone': 2965,
 '0800': 48,
 '542': 555,
 '0578': 19,
 'worry': 7559,
 'finished': 2836,
 'by': 1589,
 'march': 4320,
 'ish': 3715,
 '88066': 698,
 'lost': 4183,
 '12': 280,
 'help': 3372,
 'crickiting': 2071,
 'great': 3214,
 'fujitsu': 3009,
 'series': 5994,
 'lifebook': 4071,
 'arr': 1071,
 'birthday': 1370,
 'wish': 7494,
 'oscar': 4966,
 'gonna': 3163,
 'say': 5895,
 'normal': 4789,
 'starting': 6420,
 'panic': 5028,
 'again': 860,
 'seeing': 5957,
 'tuesday': 7026,
 'problem': 5400,
 'renewal': 5673,
 'away': 1172,
 'details': 2266,
 'very': 7229,
 'bad': 1198,
 'girl': 3116,
 'or': 4941,
 'lady': 3962,
 'actually': 808,
 'guys': 3261,
 'sunoco': 6565,
 'howard': 3488,
 'should': 6089,
 'way': 7368,
 'prolly': 5421,
 'download': 2417,
 'fring': 2982,
 'app': 1020,
 'machan': 4260,
 'once': 4902,
 'completely': 1927,
 'form': 2926,
 'clark': 1821,
 'also': 927,
 'utter': 7187,
 'waste': 7350,
 'got': 3182,
 'start': 6418,
 'howz': 3493,
 'pain': 5021,
 'down': 2416,
 'said': 5845,
 'ystrday': 7678,
 'ice': 3549,
 'medicine': 4389,
 'hmm': 3421,
 'shall': 6030,
 'bring': 1507,
 'bottle': 1450,
 'wine': 7480,
 'keep': 3876,
 'us': 7172,
 'amused': 956,
 'joking': 3812,
 'red': 5620,
 'white': 7446,
 'tomorrow': 6915,
 'takin': 6654,
 'linear': 4095,
 'algebra': 905,
 'aww': 1175,
 'first': 2845,
 'missed': 4482,
 'without': 7506,
 'asking': 1099,
 'maybe': 4366,
 'reboot': 5593,
 'ym': 7655,
 'seen': 5962,
 'buzz': 1583,
 'hi': 3395,
 'darlin': 2154,
 'london': 4158,
 'been': 1295,
 'smashed': 6216,
 'into': 3680,
 'another': 981,
 'driver': 2440,
 'big': 1352,
 'dent': 2235,
 'missing': 4484,
 'what': 7426,
 'xxx': 7613,
 'ned': 4698,
 'toa': 6889,
 'payoh': 5094,
 'while': 7443,
 'return': 5732,
 'smth': 6236,
 'wat': 7353,
 'hero': 3386,
 'leaving': 4034,
 'qatar': 5486,
 'tonite': 6925,
 'apt': 1044,
 'opportunity': 4932,
 'touch': 6953,
 'email': 2555,
 'kerala': 3884,
 'lol': 4154,
 'forgot': 2923,
 'eh': 2533,
 'someone': 6270,
 'has': 3322,
 'conacted': 1938,
 'entered': 2591,
 'phone': 5154,
 'because': 1282,
 'fancy': 2748,
 'landline': 3974,
 '09111030116': 254,
 'pobox12n146tf15': 5241,
 'mail': 4283,
 'fredericksburg': 2957,
 'telugu': 6716,
 'movie': 4577,
 'trying': 7015,
 'last': 3992,
 'weekends': 7395,
 'draw': 2426,
 'shows': 6102,
 '900': 721,
 'guaranteed': 3243,
 '09061701851': 201,
 'code': 1875,
 'k61': 3847,
 'valid': 7199,
 '12hours': 289,
 've': 7216,
 'reached': 5564,
 'finally': 2826,
 'little': 4121,
 'pocy': 5253,
 'bell': 1316,
 'neft': 4705,
 'transaction': 6971,
 'rs': 5804,
 'decimal': 2191,
 'credited': 2064,
 'beneficiary': 1325,
 'account': 787,
 'dollars': 2388,
 'ill': 3575,
 '2mrw': 408,
 'ninish': 4754,
 'address': 817,
 'icky': 3551,
 'american': 939,
 'freek': 2963,
 'wont': 7539,
 'callin': 1616,
 'jen': 3778,
 'pa': 5010,
 'self': 5969,
 'drive': 2439,
 'sch': 5908,
 'gram': 3199,
 'usually': 7186,
 'runs': 5824,
 'eighth': 2536,
 'smarter': 6215,
 'though': 6821,
 'gets': 3098,
 'almost': 920,
 'whole': 7450,
 'second': 5943,
 'smaller': 6212,
 'capacity': 1643,
 'quite': 5505,
 'ex': 2670,
 'bothering': 1449,
 'trust': 7010,
 'answers': 988,
 'men': 4411,
 'shorter': 6085,
 'ladies': 3961,
 'gaze': 3070,
 'doctor': 2369,
 'tiring': 6865,
 'uni': 7111,
 'starts': 6421,
 'taking': 6655,
 'modules': 4529,
 'concentrating': 1940,
 'project': 5419,
 'official': 4867,
 'england': 2580,
 'poly': 5265,
 'ringtone': 5761,
 'colour': 1893,
 'flag': 2854,
 'yer': 7645,
 'tonights': 6924,
 'tone': 6917,
 '84199': 671,
 'optout': 4940,
 'txt': 7048,
 'eng': 2576,
 'box39822': 1466,
 'w111wx': 7288,
 'doing': 2383,
 'settled': 6007,
 'new': 4727,
 'school': 5910,
 'year': 7636,
 'wishin': 7497,
 'friends': 2979,
 'em': 2554,
 'someplace': 6272,
 'tot': 6949,
 'shirt': 6064,
 'moved': 4575,
 'in2': 3604,
 'pub': 5456,
 'cud': 2096,
 'appt': 1040,
 'fault': 2766,
 'twice': 7041,
 'networking': 4720,
 'technical': 6702,
 'support': 6579,
 'associate': 1109,
 'ho': 3426,
 'type': 7061,
 'words': 7548,
 'wake': 7312,
 'long': 4161,
 'ago': 869,
 'dunno': 2474,
 'other': 4968,
 'thing': 6800,
 'moji': 4531,
 'informed': 3638,
 'saved': 5891,
 'lives': 4126,
 'pass': 5067,
 '69669': 589,
 'collect': 1886,
 'polyphonic': 5270,
 'gprs': 3191,
 'charges': 1729,
 'apply': 1029,
 'enjoy': 2582,
 'tones': 6918,
 'unable': 7084,
 'bhaskar': 1346,
 'deep': 2201,
 'thanx': 6767,
 'puttin': 5483,
 'da': 2132,
 'fone': 2898,
 'cool': 1997,
 'few': 2796,
 'nice': 4740,
 'ready': 5572,
 'thursday': 6840,
 'gautham': 3064,
 'swhrt': 6617,
 'dey': 2277,
 '2day': 388,
 'miss': 4480,
 'kicks': 3897,
 'private': 5391,
 '2004': 352,
 'statement': 6426,
 '07742676969': 30,
 '786': 623,
 'unredeemed': 7130,
 'points': 5257,
 '08719180248': 155,
 'identifier': 3560,
 '45239': 504,
 'expires': 2702,
 'under': 7096,
 'standing': 6410,
 'need': 4699,
 'coz': 2039,
 'before': 1301,
 'theatre': 6776,
 'watch': 7354,
 'unlimited': 7125,
 'movies': 4578,
 'pay': 5086,
 'ful': 3010,
 'song': 6288,
 'lyrics': 4245,
 'congrats': 1957,
 '3g': 462,
 'videophones': 7241,
 'yours': 7671,
 '09061744553': 206,
 'videochat': 7240,
 'wid': 7460,
 'mates': 4346,
 'java': 3766,
 'games': 3046,
 'dload': 2360,
 'polyh': 5268,
 'music': 4627,
 'noline': 4776,
 'rentl': 5677,
 'bx420': 1587,
 'ip4': 3697,
 '5we': 566,
 '150pm': 308,
 'try': 7013,
 'rebooting': 5594,
 'senthil': 5990,
 'group': 3232,
 'company': 1917,
 'apnt': 1014,
 '5pm': 563,
 'dare': 2150,
 'change': 1718,
 'ring': 5758,
 'baby': 1192,
 'stretch': 6482,
 'open': 4921,
 'pussy': 5480,
 'alright': 925,
 'sure': 6586,
 'sunshine': 6568,
 'quiz': 5507,
 'wkly': 7516,
 'sony': 6290,
 'dvd': 2482,
 'player': 5211,
 'country': 2028,
 'algarve': 904,
 'ansr': 983,
 '82277': 652,
 'sp': 6323,
 'tyrone': 7063,
 'darren': 2157,
 'considering': 1967,
 'mah': 4278,
 'ask': 1095,
 'elsewhere': 2553,
 'eat': 2501,
 'testing': 6739,
 'card': 1650,
 'network': 4719,
 'sis': 6155,
 'bathing': 1249,
 'bathe': 1248,
 'disturb': 2350,
 'cleaning': 1830,
 'night': 4747,
 'lemme': 4046,
 'around': 1070,
 'remember': 5661,
 'whom': 7451,
 'hurt': 3525,
 'during': 2478,
 'days': 2167,
 'satanic': 5879,
 'imposter': 3597,
 'price': 5376,
 'may': 4364,
 'destiny': 2264,
 'pray': 5338,
 'sura': 6585,
 'sun': 6559,
 'tv': 7037,
 'latest': 3998,
 'scrounge': 5930,
 'ammo': 945,
 'ak': 891,
 'part': 5056,
 'checking': 1752,
 'iq': 3702,
 'left': 4037,
 'orchard': 4948,
 'battery': 1252,
 'low': 4210,
 'wherever': 7438,
 'divorce': 2355,
 'she': 6044,
 'gep': 3091,
 'bus': 1566,
 'apples': 1027,
 'pairs': 5024,
 'malarky': 4297,
 'va': 7194,
 'todays': 6895,
 '800': 633,
 '09050000460': 167,
 'land': 3972,
 'line': 4094,
 'j89': 3743,
 'box245c2150pm': 1461,
 'online': 4908,
 'job': 3798,
 'bday': 1270,
 'april': 1042,
 'oooh': 4917,
 'bed': 1288,
 'ridden': 5752,
 'ey': 2717,
 'thinking': 6805,
 'hoping': 3463,
 'langport': 3980,
 'tonight': 6923,
 'gnarls': 3137,
 'barkleys': 1231,
 'crazy': 2056,
 'totally': 6951,
 'auto': 1149,
 'correct': 2008,
 'yesterday': 7648,
 'awaiting': 1168,
 'collection': 1889,
 '09061702893': 202,
 'acl03530150pm': 793,
 'denying': 2240,
 'please': 5218,
 'bahamas': 1204,
 'callfreefone': 1615,
 '08081560665': 62,
 'speak': 6335,
 'operator': 4928,
 'either': 2539,
 'cruise': 2081,
 '2000': 350,
 '18': 321,
 '07786200117': 34,
 'pick': 5168,
 'macha': 4259,
 'upset': 7154,
 'assume': 1111,
 'mindset': 4457,
 'believe': 1314,
 'wonderful': 7536,
 'plans': 5206,
 'both': 1447,
 'begin': 1306,
 'later': 3997,
 '448712404000': 499,
 '08712404000': 112,
 'immediately': 3589,
 'look': 4165,
 'dhanush': 2279,
 'rocks': 5776,
 'well': 7407,
 'leave': 4032,
 'wait': 7308,
 'superior': 6572,
 'shop': 6076,
 'drop': 2445,
 '10k': 266,
 '5k': 559,
 'travel': 6980,
 'voucher': 7281,
 '09064011000': 215,
 'ntt': 4815,
 'cr01327bt': 2042,
 'fixedline': 2852,
 'cost': 2014,
 '150ppm': 310,
 'vary': 7209,
 'general': 3082,
 'oz': 5009,
 'dude': 2465,
 'afraid': 850,
 'coming': 1907,
 'usf': 7181,
 'guess': 3249,
 'might': 4442,
 'car': 1649,
 'seems': 5961,
 'unnecessarily': 7127,
 'hostile': 3474,
 'print': 5383,
 'outs': 4984,
 'consent': 1965,
 'forms': 2930,
 'vote': 7278,
 'sing': 6145,
 'along': 922,
 'stars': 6416,
 'karaoke': 3864,
 'norm': 4787,
 '15': 303,
 'st': 6398,
 'tests': 6740,
 'library': 4065,
 'point': 5256,
 'letter': 4059,
 'access': 778,
 'til': 6855,
 'better': 1335,
 'move': 4574,
 'snowboarding': 6249,
 ...}

In [43]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [44]:
np.where(X_train_np[0] != 0)

(array([ 258,  354,  694, 1271, 2106, 2568, 2805, 3364, 5687, 5980, 5999,
        6460, 6773, 6888, 7396, 7437, 7471, 7474, 7555]),)

In [46]:
X_train[:4][1978]

'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service'

In [51]:
vec.get_feature_names_out()[2106]

'cup'

In [52]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [54]:
X_test_cv = vec.transform(X_test)

In [56]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [57]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_cv = vec.transform(emails)
pred = model.predict(emails_cv)

pred

array([0, 1])

In [58]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [59]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [61]:
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

# Exercise

- In this Exercise, you are going to classify whether a given movie review is positive or negative.
- you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [1]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

About Data: IMDB Dataset
Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download

This data consists of two columns. - review - sentiment
Reviews are the statements given by users after watching the movie.
sentiment feature tells whether the given review is positive or negative.

In [2]:
df = pd.read_csv("imdb.csv", on_bad_lines='warn')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape

(50000, 2)

In [4]:
df["positive"] = df['sentiment'].apply(lambda x: 1 if x == "positive" else 0)

In [5]:
df.head()

                                              review sentiment  positive
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [6]:
df.positive.value_counts()

positive
1    25000
0    25000
Name: count, dtype: int64

In [7]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.review, df.positive, test_size=0.2, random_state=42)

In [8]:
X_train.shape

(40000,)

In [9]:
X_train.head()[39087]

'That\'s what I kept asking myself during the many fights, screaming matches, swearing and general mayhem that permeate the 84 minutes. The comparisons also stand up when you think of the one-dimensional characters, who have so little depth that it is virtually impossible to care what happens to them. They are just badly written cyphers for the director to hang his multicultural beliefs on, a topic that has been done much better in other dramas both on TV and the cinema.<br /><br />I must confess, I\'m not really one for spotting bad performances during a film, but it must be said that Nichola Burley (as the heroine\'s slutty best friend) and Wasim Zakir (as the nasty, bullying brother) were absolutely terrible. I don\'t know what acting school they graduated from, but if I was them I\'d apply for a full refund post haste. Only Samina Awan in the lead role manages to impress in a cast of so-called British talent that we\'ll probably never hear from again. At least, that\'s the hope. Next time, hire a different scout.<br /><br />Another intriguing thought is the hideously fashionable soundtrack featuring the likes of Snow Patrol, Ian Brown and Keane. Now, I\'m a bit of a music fan and I\'m familiar with most of these artists output, but I didn\'t recognise any of the tracks during this movie (apart from the omnipresent "Run"). B-sides, anyone? We get many, many musical montages which telegraph how we\'re suppose to feel. These are accompanied by such startlingly original images as couples kissing by a swollen lake and canoodling in doorways. This is a problem, as none of the songs convey the mood efficiently, and we realise the director lacks the ability to carry the emotional journey to the audience through storytelling and dialogue alone.<br /><br />The ending is presumably meant to be just desserts, as everybody gets their comeuppance and there is at least one big shock in store.. But I remained resolutely unmoved because the script had given me no-one to root for. It\'s not enough to tackle a hot-button issue, you have to actually give us a plot that hasn\'t already been done to death and individuals who are more than window dressing. As it stands, this film is a noble failure, with only the promising lead actress and a few mildly diverting punch-ups to save it from the bin. 4/10. Must try harder..'

In [10]:
# BoWs
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train)

In [14]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [16]:
np.where(X_train_cv[0].toarray() != 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([   49,  1202,  1600,  1712,  1868,  2072,  2112,  2121,  2701,
         3497,  3533,  3544,  4094,  4435,  4647,  4661,  4707,  4894,
         5151,  5534,  5570,  5687,  5927,  6180,  6529,  6868,  6909,
         7934,  8088,  8196,  8404,  8836,  8890,  9098,  9220,  9383,
        10731, 10934, 11486, 11663, 11683, 12092, 12257, 12409, 12460,
        12515, 12827, 13126, 13361, 13601, 13755, 14592, 15647, 16938,
        17153, 17563, 18236, 18861, 20187, 20918, 22019, 22266, 22639,
        22757, 22797, 22932, 23090, 23848, 24232, 24258, 24370, 24726,
        24881, 25421, 26065, 26770, 26986, 27188, 28148, 29134, 29276,
        29301, 29544, 29768, 29820, 30117, 30257, 30318, 31436, 32212,
        32323, 32500, 33523, 33780, 33790, 34187, 34191, 35098, 36386,
        36819, 36905, 36963, 37171, 37193, 37217, 37326, 37530, 38073,
        38261, 38497, 38516, 39128, 39336, 39446, 40055, 40240, 40420,
        40723, 40749, 40819, 41227, 42344, 42704, 42814, 42829, 43991,
        44258, 44845, 45010, 45511, 45755, 46474, 46599, 47268, 47332,
        48112, 48457, 48532, 50443, 50725, 51331, 51591, 51963, 52009,
        53100, 53425, 54305, 54379, 54511, 54713, 54894, 55022, 55158,
        55381, 55382, 55421, 55549, 55950, 56515, 56610, 56665, 56983,
        56995, 57119, 57309, 57414, 58067, 58381, 58386, 58407, 58435,
        58819, 59000, 59174, 60659, 61293, 61363, 62760, 63510, 64140,
        64389, 64407, 64647, 65274, 66756, 66825, 66852, 67090, 67500,
        67904, 68482, 69765, 69938, 70451, 70862, 71074, 71554, 72020,
        72255, 72310, 72382, 74131, 74607, 75732, 76123, 76183, 76568,
        76794, 77507, 77914, 77938, 78072, 78668, 78715, 79511, 80055,
        80430, 80591, 80924, 81090, 81773, 82068, 82250, 82276, 82298,
        82339, 82355, 82416, 82446, 82468, 82525, 82568, 82641, 82734,
        83002, 83250, 83562, 83917, 84847, 85195, 86713, 87237, 87313,
        87426, 88691, 89569, 89593, 89779, 90080, 90223, 90287, 90316,
        90487, 90834, 91044, 91642, 92267, 92450]))

In [19]:
v.get_feature_names_out()[33780]

'get'

In [20]:
# Model
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("nb", MultinomialNB())
])

clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [21]:
y_pred = clf.predict(X_test)

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      4961
           1       0.87      0.82      0.85      5039

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

In [25]:
from sklearn.ensemble import RandomForestClassifier

clf2 = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("rdm", RandomForestClassifier(n_estimators=50, criterion="entropy"))
])

clf2.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('rdm',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

In [26]:
y_pred = clf2.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      4961
           1       0.85      0.83      0.84      5039

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

In [27]:
from sklearn.neighbors import KNeighborsClassifier

clf3 = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("knn", KNeighborsClassifier(n_neighbors=10, metric="euclidean"))
])

clf3.fit(X_train, y_train)

y_pred = clf3.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.65      0.66      4961
           1       0.66      0.66      0.66      5039

    accuracy                           0.66     10000
   macro avg       0.66      0.66      0.66     10000
weighted avg       0.66      0.66      0.66     10000